name: Coverage Only

on:
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage

      - name: Run tests and generate coverage
        run: |
          PYTHONPATH=. pytest -s --cov=mymodule
          coverage xml

      - name: Report coverage
        uses: insightsengineering/coverage-action@v2
        with:
          # path: 
          token: ${{ secrets.CI_TOKEN }}
          publish: true
          threshold: 95
          diff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
