name: Coverage Only

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if ref is main or release
        run: |
          if [[ "${{ github.ref_name }}" != "main" && ! "${{ github.ref_name }}" =~ ^release/ ]]; then
            echo "Error: The branch is neither 'main' nor starts with 'release/'"
            exit 1
          fi
          echo "The branch is either 'main' or starts with 'release/'"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage

      - name: Run tests and generate coverage
        run: |
          PYTHONPATH=. pytest -s --cov=mymodule
          coverage xml

      - name: Report coverage
        uses: insightsengineering/coverage-action@v2
        with:
          # path: 
          token: ${{ secrets.CI_TOKEN }}
          publish: true
          threshold: 95
          diff: true
          diff-branch: ${{ github.ref_name }}
          diff-storage: gh-pages
          storage-subdirectory: coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
